# Generated by Django 3.2 on 2021-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('founders', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('doc_registration_unit', models.CharField(max_length=256)),
                ('register_registration_date', models.DateField()),
                ('type', models.IntegerField()),
                ('Form', models.IntegerField()),
                ('languages', models.CharField(max_length=256)),
                ('distribition_scope', models.IntegerField()),
                ('goals', models.CharField(max_length=256)),
                ('money_source', models.CharField(max_length=512)),
                ('legal_location', models.CharField(max_length=256)),
                ('legal_bank_acc', models.CharField(max_length=256)),
                ('legal_id', models.IntegerField()),
                ('location', models.CharField(max_length=256)),
                ('connection', models.CharField(max_length=512)),
                ('сertificate_number', models.CharField(max_length=32)),
                ('registration_date', models.DateField()),
                ('final_registration_unit', models.CharField(max_length=128)),
                ('duplicate_doc_name', models.CharField(max_length=128)),
                ('duplicate_doc_number', models.IntegerField()),
                ('duplicate_doc_date', models.DateField()),
                ('duplicate_doc_issued', models.CharField(max_length=128)),
                ('duplicate_date', models.DateField()),
                ('duplicate_unit', models.CharField(max_length=128)),
                ('re_registration', models.BooleanField()),
                ('termination_date', models.DateField()),
                ('termination_doc_name', models.CharField(max_length=128)),
                ('termination_doc_number', models.IntegerField()),
                ('termination_doc_issued', models.CharField(max_length=128)),
                ('additional', models.CharField(max_length=512)),
                ('registrar', models.IntegerField()),
            ],
        ),
    ]
