# Generated by Django 3.2 on 2021-05-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_rename_distribition_scope_agency_distribution_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='сertificate_number',
            new_name='certificate_number',
        ),
    ]
