# Generated by Django 3.2 on 2021-05-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_rename_сertificate_number_agency_certificate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='founders',
        ),
        migrations.AddField(
            model_name='agency',
            name='founders',
            field=models.CharField(default='founder1', max_length=512),
            preserve_default=False,
        ),
    ]
