# Generated by Django 3.2 on 2021-05-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210501_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='distribition_zone',
            new_name='distribution_zone',
        ),
    ]
