# Generated by Django 3.2 on 2021-05-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_rename_distribition_zone_media_distribution_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='expiration_doc_numbe',
            new_name='expiration_doc_number',
        ),
    ]
