# Generated by Django 3.2 on 2021-05-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_rename_expiration_doc_numbe_media_expiration_doc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='founders',
        ),
        migrations.AddField(
            model_name='media',
            name='founders',
            field=models.CharField(default='founder2', max_length=512),
            preserve_default=False,
        ),
    ]
