# Generated by Django 3.2 on 2021-05-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20210517_0821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgencyChanges',
            new_name='MediaChanges',
        ),
    ]
